const fungisidesData = [
    {
        id: 1,
        img: "https://www.dhanuka.com/storage/products/July2021/UPeVdR7FwvO6fAMkKMXa.png",
        name: "Lustre",
        price: 150,
        rating: 4.5,
        desc: "Flusilazole 12.5% + Carbendazim 25 % SE100 ml, 384 ml, 1 L",
    },
    {
        id: 2,
        img: "https://www.dhanuka.com/storage/products/August2021/mBvJKvLx6N1Zg15z3cOq.png",
        name: "Godiwa Super",
        price: 150,
        rating: 4.5,
        desc: "Azoxystrobin 18.2% + Difenoconazole 11.4% w/w SC200 ml, 500 ml, 1 L",
    },
    {
        id: 3,
        img: "https://www.dhanuka.com/storage/products/June2024/su7lMZShtw5jz3mMqLny.png",
        name: "Conika",
        price: 150,
        rating: 4.5,
        desc: "Kasugamycin 5% + Copper Oxychloride 45% WP50 gm, 100 gm, 250 gm, 500 gm, 1 Kg",
    },
    {
        id: 4,
        img: "https://www.dhanuka.com/storage/products/August2021/AlZpP1elUIEKZLN9enjM.png",
        name: "Cursor",
        price: 150,
        rating: 4.5,
        desc: "Flusilazole 40% EC50 ml, 100ml, 250 ml",
    },
    {
        id: 5,
        img: "https://www.dhanuka.com/storage/products/August2021/pg45rK89HAN2PE3HCe8H.png",
        name: "Kasu-B",
        price: 150,
        rating: 4.5,
        desc: "Kasugamycin 3% SL50 ml, 250 ml, 500 ml, 1 ltr, 2.5 ltr",
    },
    {
        id: 6,
        img: "https://www.dhanuka.com/storage/products/August2021/JyiHSNjWeQ7t0FglhNoo.png",
        name: "Sixer",
        price: 150,
        rating: 4.5,
        desc: "Carbendazim12%+ Mancozeb63%WP20 gm, 100 gm, 250 gm, 500 gm, 1 kg",
    },
    {
        id: 7,
        img: "https://www.dhanuka.com/storage/products/May2019/ldhX0y26jDzeJZbDm3e3.png",
        name: "Fujita",
        price: 150,
        rating: 4.5,
        desc: "Isoprothiolane 40% EC250 ml, 500 ml, 1 ltr",

    },
    {
        id: 8,
        img: "https://www.dhanuka.com/storage/products/July2022/u5sKUqh0ApPohadpLqz6.png",
        name: "Spectrum",
        price: 150,
        rating: 4.5,
        desc: "Azoxystrobin 11% + Tebuconazole 18.3% w/w SC100 ml, 250 ml, 500 ml, 1 ltr",

    },
    {
        id: 9,
        img: "https://www.dhanuka.com/storage/products/July2022/XK11teUXWBzQyHZ3yOlT.png",
        name: "Sheathmar",
        price: 150,
        rating: 4.5,
        desc: "Validamycin 3% L100ml, 250ml, 500ml, 1 ltr, 2.5 ltr, 5 ltr,",

    },
    {
        id: 10,
        img: "https://www.dhanuka.com/storage/products/July2022/2VicGvBITaXsQwObQ64o.webp",
        name: "Vitavax Ultra",
        price: 150,
        rating: 4.5,
        desc: "Carboxin 17.5% + Thiram 17.5% FF500 ml, 1 Ltrs",

    },
    {
        id: 11,
        img: "https://www.dhanuka.com/storage/products/July2022/nyV4w38EgB4rTBXuxdZU.webp",
        name: "Dhanuka M-45",
        price: 150,
        rating: 4.5,
        desc: "Mancozeb 75% WP100gm, 250gm, 500gm, 1kg",

    },
    {
        id: 12,
        img: "https://www.dhanuka.com/storage/products/August2021/qrw7XHvhFosoxEGWRyjn.png",
        name: "Vitavax Power",
        price: 150,
        rating: 4.5,
        desc: "Carboxin 37.5% + Thiram 37.5% WS10gm, 100gm, 250gm, 500gm, 1kg",

    },
    {
        id: 13,
        img: "https://www.dhanuka.com/storage/products/July2022/s5klhrQEvLH344PLkyU5.png",
        name: "Dhanustin",
        price: 150,
        rating: 4.5,
        desc: "Carbendazim 50% WP100 gm, 250 gm, 500 gm, 1 kg",
    },
    {
        id: 14,
        img: "https://www.dhanuka.com/storage/products/July2022/LXOqWDb8prQtiG4wUsCK.png",
        name: "Dhanucop",
        price: 150,
        desc: "Copper Oxychloride 50% WP500 gm, 25 kg",
        rating: 4.5,
    },
    {
        id: 15,
        img: "https://www.dhanuka.com/storage/products/August2021/drQ4QVdVsBNR4V6WPPWh.png",
        name: "Hexadhan Plus",
        price: 150,
        desc: "Hexaconazole 5% SC100,250,500,1,5lit",
        rating: 4.5,
    },
]
export default fungisidesData