const herbicideData = [
    {
        id: 1,
        img:"https://www.dhanuka.com/storage/products/July2022/ByQDaqrsV0rbg6S1ENvV.webp",
        name: "Targa Super" ,
        price: 150 ,
        desc:  "Quizalofop Ethyl 5% EC100 ml, 250 ml, 500 ml, 1 Ltr" ,
        rating: 4.5 ,
    },
    {
        id: 2,
        img:"https://www.dhanuka.com/storage/products/August2021/R2PUp3AYqqrbDQ8qVSUo.png",
        name: "Foster" ,
        price: 150 ,
        desc:  "Cyflumetofen 20.00% SC100 ml, 250 ml, 1 Ltr" ,
        rating: 4.5 ,
    },
    {
        id: 3,
        img:"https://www.dhanuka.com/storage/products/July2022/mrkS53hbCe6LrW18qflC.png",
        name: "Lustre" ,
        price: 150 ,
        desc:  "Flusilazole 12.5% + Carbendazim 25 % SE100 ml, 384 ml, 1 L" ,
        rating: 4.5 ,
    },
    {
        id: 4,
        img:"https://www.dhanuka.com/storage/products/August2021/NpjQyVNZfV8H6vonKuY5.png",
        name: "Sakura" ,
        price: 150 ,
        desc:  "Quizalofop Ethyl 10% EC100 ml, 150 ml, 250 ml, 450 ml, 1 Ltr" ,
        rating: 4.5 
    },
    {
        id: 5,
        img:"https://www.dhanuka.com/storage/products/August2022/S7peBTNm1w38H5rUsIBP.png",
        name: "Mortar" ,
        price: 150 ,
        desc:  "Cartap Hydrochloride 75% SG100 gm, 250 gm, 500 gm, 1 Kg" ,
        rating: 4.5 ,
    },
    {
        id: 6,
        img:"https://www.dhanuka.com/storage/products/August2021/mBvJKvLx6N1Zg15z3cOq.png",
        name: "Godiwa Super" ,
        price: 150 ,
        desc:  "Azoxystrobin 18.2% + Difenoconazole 11.4% w/w SC200 ml, 500 ml, 1 L" ,
        rating: 4.5 ,
    },
    {
        id: 7,
        img:"https://www.dhanuka.com/storage/products/June2024/TIB5UnFiKKUsUjQSqqf2.png",
        name: "Sempra" ,
        price: 150 ,
        desc:  "Halosulfuron Methyl 75% WG3.6 gm, 18 gm, 36 gm" ,
        rating: 4.5 ,
    },
    {
        id: 8,
        img:"https://www.dhanuka.com/storage/products/August2021/GduU4tDexk9aznLLc6WO.png",
        name: "Wetcit" ,
        price: 150 ,
        desc:  "Efficacy Enhancer with Orange Oil Extract15 ml, 50 ml, 100 ml, 250 ml, 500 ml, 1 Ltr" ,
        rating: 4.5 ,
    },
    {
        id: 9,
        img:"https://www.dhanuka.com/storage/products/June2024/su7lMZShtw5jz3mMqLny.png",
        name: "Conika" ,
        price: 150 ,
        desc:  "Kasugamycin 5% + Copper Oxychloride 45% WP50 gm, 100 gm, 250 gm, 500 gm, 1 Kg" ,
        rating: 4.5 ,
    },
    {
        id: 10,
        img:"https://www.dhanuka.com/storage/products/August2021/HLJAndviBVX8rULQUw8x.png",
        name: "Suelo" ,
        price: 150 ,
        desc:  "Soil Enhancer with Orange Oil Extract250 ml, 1 Ltr" ,
        rating: 4.5 ,
    },
    {
        id: 12,
        img:"https://www.dhanuka.com/storage/products/July2022/s5klhrQEvLH344PLkyU5.png",
        name: "Maxyld" ,
        price: 150 ,
        desc:  "Gibberellic Acid 0.001%100 ml, 250 ml, 500 ml & 1 ltr" ,
        rating: 4.5 ,
    },
    {
        id: 13,
        img:"https://www.dhanuka.com/storage/products/August2021/xctzKn5Uhl2Pr6Y3rddm.png",
        name: "Dhanvarsha" ,
        price: 150 ,
        desc:  "100 ml, 250 ml, 500 ml, 1 Ltr" ,
        rating: 4.7,
    },
    {
        id: 13,
        img:"https://www.dhanuka.com/storage/products/May2019/xfNaupfvVF8HmQMeUYSA.png",
        name: "Max-Soy" ,
        price: 150 ,
        desc:  "Quizalofop-ethyl 10% EC150 ml, 450 ml" ,
        rating: 4.5 ,
    },
    {
        id: 14,
        name: "Mesotrax" ,
        price: 150 ,
        rating: 4.5 ,
        desc:  "700 ml, 1400 ml, 3500 ml" ,
        img:"https://www.dhanuka.com/storage/products/June2024/wTzDrDqRYYTkmA9eogvr.png",
    },
    {
        id: 15,
        img:"https://www.dhanuka.com/storage/products/June2024/kgArkH2ZiBQqHBdw3hBE.png",
        name: "Implode" ,
        price: 150,
        rating: 4.5 ,
        desc:  "15 ml, 30 ml, 75 ml" ,
    },
    
]   
export default herbicideData